TERM = "screen-256color"
live_config_reload = true
startup_mode = "windowed"
use_thin_strokes = true

[colors.bright]
black = "#625e4c"
blue = "#9d65ff"
cyan = "#58d1eb"
green = "#98e024"
magenta = "#f4005f"
red = "#f4005f"
white = "#f6f6ef"
yellow = "#e0d561"

[colors.cursor]
cursor = "#fc971f"
text = "#000000"

[colors.normal]
black = "#1a1a1a"
blue = "#9d65ff"
cyan = "#58d1eb"
green = "#98e024"
magenta = "#f4005f"
red = "#f4005f"
white = "#c4c5b5"
yellow = "#fd971f"

[colors.primary]
background = "#0c0c0c"
foreground = "#d9d9d9"

[colors.selection]
background = "#343434"
text = "#ffffff"

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 15.0

[font.Bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.Italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[hints.enabled]]
command = "open"
post_processing = true
regex = "(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\" {-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "Command"

[[keyboard.bindings]]
key = "Comma"
mods = "Command"

[keyboard.bindings.command]
args = ["-c", "open ~/.alacritty.yml"]
program = "sh"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "©"
key = "Key1"
mods = "Alt"

[[keyboard.bindings]]
chars = "@"
key = "Key2"
mods = "Alt"

[[keyboard.bindings]]
chars = "£"
key = "Key3"
mods = "Alt"

[[keyboard.bindings]]
chars = "$"
key = "Key4"
mods = "Alt"

[[keyboard.bindings]]
chars = "∞"
key = "Key5"
mods = "Alt"

[[keyboard.bindings]]
chars = "§"
key = "Key6"
mods = "Alt"

[[keyboard.bindings]]
chars = "|"
key = "Backslash"
mods = "Alt"

[[keyboard.bindings]]
chars = "["
key = "LBracket"
mods = "Alt"

[[keyboard.bindings]]
chars = "]"
key = "RBracket"
mods = "Alt"

[[keyboard.bindings]]
chars = "≈"
key = "Key0"
mods = "Alt"

[[keyboard.bindings]]
chars = "¡"
key = "Key1"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "”"
key = "Key2"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "¥"
key = "Key3"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "¢"
key = "Key4"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "‰"
key = "Key5"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "¶"
key = "Key6"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = '\'
key = "Backslash"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "{"
key = "LBracket"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "}"
key = "RBracket"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "≠"
key = "Key0"
mods = "Alt|Shift"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 100000

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "buttonless"
dynamic_padding = true
dynamic_title = true

[window.dimensions]
columns = 0
lines = 0

[window.glyph_offset]
x = 0
y = 1

[window.offset]
x = 0
y = 2

[window.padding]
x = 15
y = 10
