#!/usr/bin/env sh

## --- Quickly restart the yabai launch agent
rctrl + ralt + rcmd + lcmd - r      : launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"

## --- rotate tree 90, toggle split
rctrl + ralt + rcmd - r             : yabai -m space --rotate 90
rctrl + ralt + rcmd + shift - r     : yabai -m window --toggle split

## --- toggle window fullscreen, float, sticky
rctrl + ralt + rcmd - space         : yabai -m window --toggle zoom-fullscreen
rctrl + ralt + rcmd + shift - space : yabai -m window --toggle zoom-parent
rctrl + ralt + rcmd - f             : yabai -m window --toggle float; yabai -m window --grid 4:4:1:1:2:2;
rctrl + ralt + rcmd + shift - s     : yabai -m window --toggle sticky

## --- toggle float for entire space
rctrl + ralt + rcmd + shift - f     : yabai -m space --layout "$([ "$(yabai -m query --spaces --space | jq '.type')" = '"bsp"' ] && echo float || echo bsp)"

## --- toggle PiP
rctrl + ralt + rcmd - p             : yabai -m window --toggle border; yabai -m window --toggle pip; yabai -m window --toggle float

## --- toggle focus_follows_mouse
rctrl + ralt + rcmd - m             : [[ $(yabai -m config focus_follows_mouse) = "disabled" ]] && yabai -m config focus_follows_mouse autofocus || yabai -m config focus_follows_mouse off

## --- resize windows
rctrl + ralt + rcmd - a             : yabai -m window --resize left:-20:0  || yabai -m window --resize right:-20:0
rctrl + ralt + rcmd - s             : yabai -m window --resize bottom:0:20 || yabai -m window --resize top:0:20
rctrl + ralt + rcmd - w             : yabai -m window --resize top:0:-20   || yabai -m window --resize bottom:0:-20
rctrl + ralt + rcmd - d             : yabai -m window --resize right:20:0  || yabai -m window --resize left:20:0

## --- shift focus of windows
rctrl + ralt + rcmd + lcmd - h      : yabai -m window --focus west
rctrl + ralt + rcmd + lcmd - j      : yabai -m window --focus south
rctrl + ralt + rcmd + lcmd - k      : yabai -m window --focus north
rctrl + ralt + rcmd + lcmd - l      : yabai -m window --focus east
rctrl + ralt + rcmd + lcmd - n      : yabai -m window --focus next
rctrl + ralt + rcmd + lcmd - m      : yabai -m window --focus prev

## --- swap with previous or next window in window tree
rctrl + ralt + rcmd + shift - h     : yabai -m window --swap west
rctrl + ralt + rcmd + shift - j     : yabai -m window --swap south
rctrl + ralt + rcmd + shift - k     : yabai -m window --swap north
rctrl + ralt + rcmd + shift - l     : yabai -m window --swap east

## --- set insertion point in focused container
rctrl + ralt + rcmd  - left         : yabai -m window --insert west
rctrl + ralt + rcmd  - down         : yabai -m window --insert south
rctrl + ralt + rcmd  - up           : yabai -m window --insert north
rctrl + ralt + rcmd  - right        : yabai -m window --insert east

# Focus window up/down in stack
rctrl + ralt + rcmd - z             : yabai -m window --focus stack.next || yabai -m window --focus stack.first
rctrl + ralt + rcmd - q             : yabai -m window --focus stack.prev || yabai -m window --focus stack.last
rctrl + ralt + rcmd - u             : yabai -m window --toggle float; yabai -m window --toggle float

# Add the active window  to the window or stack to the {direction}
# Note that this only works when the active window does *not* already belong to a stack
rctrl + ralt + rcmd + lctrl - h     : yabai -m window west --stack $(yabai -m query --windows --window | jq -r '.id')
rctrl + ralt + rcmd + lctrl - j     : yabai -m window south --stack $(yabai -m query --windows --window | jq -r '.id')
rctrl + ralt + rcmd + lctrl - k     : yabai -m window north --stack $(yabai -m query --windows --window | jq -r '.id')
rctrl + ralt + rcmd + lctrl - l     : yabai -m window east --stack $(yabai -m query --windows --window | jq -r '.id')

## --- switch spaces
rctrl + ralt + rcmd - 1             : yabai -m space --focus 1
rctrl + ralt + rcmd - 2             : yabai -m space --focus 2
rctrl + ralt + rcmd - 3             : yabai -m space --focus 3
rctrl + ralt + rcmd - 4             : yabai -m space --focus 4
rctrl + ralt + rcmd - 5             : yabai -m space --focus 5
rctrl + ralt + rcmd - 6             : yabai -m space --focus 6
rctrl + ralt + rcmd - 7             : yabai -m space --focus 7
rctrl + ralt + rcmd - 8             : yabai -m space --focus 8
rctrl + ralt + rcmd - tab           : yabai -m space --focus recent


## --- send to space
rctrl + ralt + rcmd + shift - 1     : yabai -m window --space 1
rctrl + ralt + rcmd + shift - 2     : yabai -m window --space 2
rctrl + ralt + rcmd + shift - 3     : yabai -m window --space 3
rctrl + ralt + rcmd + shift - 4     : yabai -m window --space 4
rctrl + ralt + rcmd + shift - 5     : yabai -m window --space 5
rctrl + ralt + rcmd + shift - 6     : yabai -m window --space 6
rctrl + ralt + rcmd + shift - 7     : yabai -m window --space 7
rctrl + ralt + rcmd + shift - 8     : yabai -m window --space 8

## --- send to space and focus
rctrl + ralt + rcmd + lcmd - 1      : yabai -m window --space 1; yabai -m space --focus 1
rctrl + ralt + rcmd + lcmd - 2      : yabai -m window --space 2; yabai -m space --focus 2
rctrl + ralt + rcmd + lcmd - 3      : yabai -m window --space 3; yabai -m space --focus 3
rctrl + ralt + rcmd + lcmd - 4      : yabai -m window --space 4; yabai -m space --focus 4
rctrl + ralt + rcmd + lcmd - 5      : yabai -m window --space 5; yabai -m space --focus 5
rctrl + ralt + rcmd + lcmd - 6      : yabai -m window --space 6; yabai -m space --focus 6
rctrl + ralt + rcmd + lcmd - 7      : yabai -m window --space 7; yabai -m space --focus 7
rctrl + ralt + rcmd + lcmd - 8      : yabai -m window --space 8; yabai -m space --focus 8


## --- launch apps
rctrl + ralt + rcmd - return        : osascript /Users/jonathan/code/dotfiles/yabai/NewiTermWindow.applescript
# rctrl + ralt + rcmd - return        : open -na Alacritty
# rctrl + ralt + rcmd - return        : /Applications/Kitty.app/Contents/MacOS/kitty --single-instance -d ~
rctrl + ralt + rcmd + lcmd - return : MOZ_DISABLE_SAFE_MODE_KEY=1 /Applications/Firefox.app/Contents/MacOS/Firefox
rctrl + ralt + rcmd + lcmd - c      : code -n
rctrl + ralt + rcmd + lcmd - f      : open $HOME



####### switch monitor input to HDMI-2

#rctrl + ralt + rcmd - numpad_enter  : ddcctl -d 1 -i 18
rctrl + ralt + rcmd - home             : /Users/jonathanwalter/bin/monitor-input.sh