#!/usr/bin/env sh

### Load scripting additions for Big Sur ONLY
if [[ $(uname -r | cut -d"." -f1) == "20" ]]; then 
    sudo yabai --load-sa;
    yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa";
fi

# Custom space names
yabai -m space 1 --label one
yabai -m space 2 --label two
yabai -m space 3 --label three
yabai -m space 4 --label four
yabai -m space 5 --label five
yabai -m space 6 --label six
yabai -m space 7 --label se7en
yabai -m space 8 --label eight*

# float space 8
yabai -m config --space 8 layout float


# app specific settings
yabai -m rule --add app="^System Preferences$" layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" layer=above manage=off
yabai -m rule --add app="^System Information$" layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" layer=above manage=off
yabai -m rule --add app="^Archive Manager$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^console$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Installer$" manage=off
yabai -m rule --add app="^BetterTouchTool$" manage=off
yabai -m rule --add app=".*" title="Preferences" manage=off layer=above
yabai -m rule --add app=".*" title="Software Update" manage=off layer=above
yabai -m rule --add app="^Digital Colou?r Meter$" manage=off
yabai -m rule --add app="^Firefox$" title="^Opening .*" layer=above manage=off
yabai -m rule --add app="^Discord$" title="Discord Updater" manage=off


# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               on # floating windows on top
yabai -m config window_shadow                on
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.2
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.9

yabai -m config window_border                on
yabai -m config window_border_width          5
yabai -m config active_window_border_color   0xffFAD636
yabai -m config normal_window_border_color   0xff000000
yabai -m config insert_feedback_color        0xffFAD636

if [[ $(hostname -s) == "jonathan-mbp" ]]; then 
    yabai -m config mouse_modifier           fn
else
    yabai -m config mouse_modifier           ctrl
fi

yabai -m config split_ratio                  0.6
yabai -m config auto_balance                 off
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  20
# yabai -m config bottom_padding               6
# yabai -m config left_padding                 6
# yabai -m config right_padding                6
# yabai -m config window_gap                   12
yabai -m config bottom_padding               20
yabai -m config left_padding                 40
yabai -m config right_padding                40
yabai -m config window_gap                   20

# top bar pading
yabai -m config external_bar                 all:30:0




yabai -m signal --add event=window_destroyed action="$HOME/dotfiles/yabai/window-focus-on-destroy.sh"


# Übersicht simple-bar refresh widgets

# Refresh widgets on space change
yabai -m signal --add event=space_changed action="$HOME/dotfiles/yabai/ubersicht-refresh-spaces.applescript; $HOME/dotfiles/yabai/ubersicht-refresh-process.applescript"
# Refresh widgets on display focus change
yabai -m signal --add event=display_changed action="$HOME/dotfiles/yabai/ubersicht-refresh-spaces.applescript; $HOME/dotfiles/yabai/ubersicht-refresh-process.applescript"
# Refresh widgets on window resize
yabai -m signal --add event=window_resized action="$HOME/dotfiles/yabai/ubersicht-refresh-spaces.applescript"
# Refresh widgets on when focused application changes
yabai -m signal --add event=window_focused action="$HOME/dotfiles/yabai/ubersicht-refresh-spaces.applescript; $HOME/dotfiles/yabai/ubersicht-refresh-process.applescript"
# Refresh widgets on when focused application changes
yabai -m signal --add event=application_front_switched action="$HOME/dotfiles/yabai/ubersicht-refresh-spaces.applescript; $HOME/dotfiles/yabai/ubersicht-refresh-process.applescript"
# Refresh widgets on when an application window is closed
yabai -m signal --add event=window_destroyed action="$HOME/dotfiles/yabai/ubersicht-refresh-spaces.applescript; $HOME/dotfiles/yabai/ubersicht-refresh-process.applescript"
# Refresh process widget when current window title changes
yabai -m signal --add event=window_title_changed action="$HOME/dotfiles/yabai/ubersicht-refresh-process.applescript"


echo "yabai configuration loaded.."