#!/usr/bin/env sh

# Custom space names
yabai -m space 1 --label one*
yabai -m space 2 --label two
yabai -m space 3 --label three
yabai -m space 4 --label four
yabai -m space 5 --label five
yabai -m space 6 --label six
yabai -m space 7 --label se7en
yabai -m space 8 --label eight*

# float space 1 and 8
yabai -m config --space 1 layout float
yabai -m config --space 8 layout float


# app specific settings
yabai -m rule --add app="^System Preferences$" layer='above' manage='off'
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" layer=above manage=off
yabai -m rule --add app="^System Information$" layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" layer=above manage=off
yabai -m rule --add app="^Archive Manager$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^console$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Installer$" manage=off
yabai -m rule --add app="^BetterTouchTool$" manage=off
yabai -m rule --add app=".*" title="Preferences" manage=off layer=above
yabai -m rule --add app=".*" title="Settings" manage=off layer=above
yabai -m rule --add app=".*" title="Software Update" manage=off layer=above
yabai -m rule --add app="^Digital Colou?r Meter$" manage=off
yabai -m rule --add app="^Firefox$" title="^Opening .*" layer=above manage=off
#yabai -m rule --add app="^Finder$" title="^.* Info$" layer=above manage=off
#yabai -m rule --add app="^Finder$" title="^Copy$" layer=above manage=off
yabai -m rule --add app="^Discord$" title="Discord Updater" manage=off
yabai -m rule --add app="^Tor Browser" manage=off # tiling affects window size, which gives information
yabai -m rule --add app="^DaVinci Resolve$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^SonicWall Mobile Connect$" manage=off


# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off # or 'autofocus'
yabai -m config window_placement             second_child
yabai -m config window_shadow                on
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.2
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0

yabai -m config window_border                off
yabai -m config window_border_width          5
yabai -m config active_window_border_color   0xffFAD636
yabai -m config normal_window_border_color   0xff000000
yabai -m config insert_feedback_color        0xffFAD636

yabai -m config mouse_modifier           ctrl

yabai -m config split_ratio                  0.55
yabai -m config auto_balance                 off
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10


# focus window on destroy
# yabai -m signal --add event=window_destroyed action="$HOME/dotfiles/yabai/window-focus-on-destroy.sh"
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus recent || yabai -m window --focus first"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus recent || yabai -m window --focus first"

echo "yabai configuration loaded.."