# load zgen
source "${HOME}/.zgen/zgen.zsh"

# if the init scipt doesn't exist
if ! zgen saved; then
  echo "Creating a zgen save"

  # load oh-my-zsh
  zgen oh-my-zsh

  # oh-my-zsh plugins
  zgen oh-my-zsh plugins/git
  zgen oh-my-zsh plugins/colored-man-pages
  zgen oh-my-zsh plugins/colorize 
  # zgen oh-my-zsh plugins/command-not-found
  zgen oh-my-zsh plugins/catimg
  zgen oh-my-zsh plugins/compleat
  zgen oh-my-zsh plugins/docker
  zgen oh-my-zsh plugins/extract
  # zgen oh-my-zsh plugins/rsync
  # zgen oh-my-zsh plugins/screen
  zgen oh-my-zsh plugins/sudo
  # zgen oh-my-zsh plugins/sublime

  # osx specific plugins
  if [[ $(uname) = "Darwin" ]]; then
    # zgen oh-my-zsh plugins/brew
    # zgen oh-my-zsh plugins/osx
  fi

  # oh-my-zsh theme
  # zgen oh-my-zsh themes/steeef
  # zgen load denysdovhan/spaceship-prompt spaceship
  zgen load yardnsm/blox-zsh-theme

  # syntax highlight
  zgen load zsh-users/zsh-syntax-highlighting

  # completions
  zgen load zsh-users/zsh-autosuggestions
  zgen load zsh-users/zsh-history-substring-search
  zgen load zsh-users/zsh-completions src

  autoload -U bashcompinit && bashcompinit
  source /usr/local/etc/bash_completion.d/az

  # other plugins
  zgen load djui/alias-tips

  # generate the init script from plugins above
  zgen save
fi

# thefuck
eval "$(thefuck --alias)"

# make dir and cd into it
function mde() {
  if [ "$#" -eq "1" ]
  then
    mkdir -p $1 && cd $1
  else
    echo "Need exactly one argument"
  fi
}

# Auto-reload for zgen
ZGEN_RESET_ON_CHANGE=(${HOME}/.zshrc ${HOME}/.zshrc.local)

# Homebrew path
export PATH="/usr/local/sbin:$PATH"

# add ~/bin to path
export PATH="$HOME/bin:$PATH"

# iterm shell integration
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# load zshrc_local
test -e "${HOME}/.zshrc_local" && source "${HOME}/.zshrc_local"

# theme settings
BLOX_BLOCK__CWD_TRUNC=5

# pyenv-virtualenv
if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi

# linux specific stuff
if [[ $(uname) = "Linux" ]]; then
  source ~/.profile
fi

# gitignore.io api
function gi() { 
  curl -L -s https://www.gitignore.io/api/$@
}