
#### FIG ENV VARIABLES ####
# Please make sure this block is at the start of this file.
[ -s ~/.fig/shell/pre.sh ] && source ~/.fig/shell/pre.sh
#### END FIG ENV VARIABLES ####
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

zmodload zsh/zprof
# load zgen
source "${HOME}/.zgen/zgen.zsh"

# if the init scipt doesn't exist
if ! zgen saved; then
  echo "Creating a zgen save"

  # load oh-my-zsh
  zgen oh-my-zsh

  # oh-my-zsh plugins
  zgen oh-my-zsh plugins/autojump
  zgen oh-my-zsh plugins/asdf
  zgen oh-my-zsh plugins/git
  zgen oh-my-zsh plugins/colored-man-pages
  zgen oh-my-zsh plugins/docker
  zgen oh-my-zsh plugins/extract
  zgen oh-my-zsh plugins/sudo
  zgen oh-my-zsh plugins/catimg
  # zgen oh-my-zsh plugins/colorize 
  # zgen oh-my-zsh plugins/command-not-found
  # zgen oh-my-zsh plugins/compleat

  # osx specific plugins
  if [[ $(uname) = "Darwin" ]]; then
    # zgen oh-my-zsh plugins/brew
    # zgen oh-my-zsh plugins/osx
    zgen load Amar1729/yabai-zsh-completions
  fi

  # oh-my-zsh theme
  zgen load romkatv/powerlevel10k powerlevel10k

  # syntax highlight
  zgen load zsh-users/zsh-syntax-highlighting

  # completions
  zgen load zsh-users/zsh-autosuggestions
  zgen load zsh-users/zsh-history-substring-search
  zgen load zsh-users/zsh-completions src

  # other plugins
  zgen load djui/alias-tips
  zgen load jeanpantoja/dotpyvenv

  # generate the init script from plugins above
  zgen save
fi

# enable bash autocomplete
autoload -U +X bashcompinit && bashcompinit

# Azure-cli autocomplete
test -e "/usr/local/etc/bash_completion.d/az" && source /usr/local/etc/bash_completion.d/az

# autojump tab completion
[ -f /usr/local/etc/profile.d/autojump.sh ] && source /usr/local/etc/profile.d/autojump.sh

# thefuck
if which thefuck > /dev/null; then eval "$(thefuck --alias)"; fi


# make dir and cd into it
function mde() {
  if [ "$#" -eq "1" ]
  then
    mkdir -p $1 && cd $1
  else
    echo "Need exactly one argument"
  fi
}

# gitignore.io api
function gi() { 
  curl -L -s https://www.gitignore.io/api/$@
}

# make python3 virtual environment
function mkvenv() {
  python3 -m venv venv
  source venv/bin/activate
}

# Auto-reload for zgen
ZGEN_RESET_ON_CHANGE=(${HOME}/.zshrc ${HOME}/.zshrc.local)

# Homebrew path
export PATH="/usr/local/sbin:$PATH"

# Go paths
if which go > /dev/null; then export GOPATH=$(go env GOPATH); export PATH=$PATH:$(go env GOPATH)/bin; fi

# add ~/bin to path
export PATH="$HOME/bin:$PATH"

# asdf
test -e "/usr/local/opt/asdf/libexec/asdf.sh" && source "/usr/local/opt/asdf/libexec/asdf.sh"

# iterm shell integration
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# load zshrc_local
test -e "${HOME}/.zshrc_local" && source "${HOME}/.zshrc_local"

# load alias file
test -e "${HOME}/.alias" && source "${HOME}/.alias"

# load local alias file
test -e "${HOME}/.alias_local" && source "${HOME}/.alias_local"

# linux specific stuff
if [[ $(uname) = "Linux" ]]; then
  source ~/.profile
fi

# osx specific stuff
if [[ $(uname) = "Darwin" ]]; then
  # see https://github.com/mobile-shell/mosh/issues/98#issuecomment-347985957
  export LC_CTYPE=en_US.UTF-8
  export LC_ALL=en_US.UTF-8
fi

# make gpg work
if which gpg > /dev/null; then export GPG_TTY=$(tty); fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

#### FIG ENV VARIABLES ####
# Please make sure this block is at the end of this file.
[ -s ~/.fig/fig.sh ] && source ~/.fig/fig.sh
#### END FIG ENV VARIABLES ####
